"""add farm task states

Revision ID: 4ca33eadf1b0
Revises: e4e166da840d
Create Date: 2026-07-13 11:43:50.144660
"""

from alembic import op
import sqlalchemy as sa

revision = '4ca33eadf1b0'
down_revision = 'e4e166da840d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_task_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'task_id')
    )
    op.create_index(op.f('ix_farm_task_states_farm_id'), 'farm_task_states', ['farm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_task_states_farm_id'), table_name='farm_task_states')
    op.drop_table('farm_task_states')
    # ### end Alembic commands ###
