"""add crop plantings

Revision ID: 7ac49845d33b
Revises: 5478c98fc9ee
Create Date: 2026-07-13 11:18:24.594796
"""

from alembic import op
import sqlalchemy as sa

revision = '7ac49845d33b'
down_revision = '5478c98fc9ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_plantings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=120), nullable=False),
    sa.Column('planted_on', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_plantings_farm_id'), 'crop_plantings', ['farm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_plantings_farm_id'), table_name='crop_plantings')
    op.drop_table('crop_plantings')
    # ### end Alembic commands ###
