"""add farm playbooks

Revision ID: e4e166da840d
Revises: 7ac49845d33b
Create Date: 2026-07-13 11:28:59.345975
"""

from alembic import op
import sqlalchemy as sa

revision = 'e4e166da840d'
down_revision = '7ac49845d33b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_playbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'trigger')
    )
    op.create_index(op.f('ix_farm_playbooks_farm_id'), 'farm_playbooks', ['farm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_playbooks_farm_id'), table_name='farm_playbooks')
    op.drop_table('farm_playbooks')
    # ### end Alembic commands ###
