"""configure succession intervals

Revision ID: ed6722bc329f
Revises: 4ca33eadf1b0
Create Date: 2026-07-13 12:08:45.340168
"""

from alembic import op
import sqlalchemy as sa

revision = 'ed6722bc329f'
down_revision = '4ca33eadf1b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_plantings', sa.Column('succession_interval_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crop_plantings', 'succession_interval_days')
    # ### end Alembic commands ###
